name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Magpylib version
      description: What version of Magpylib are you running?
      options:
        - 4.x (Latest)   
        - 3.x
        - 2.x
        - 1.x
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see! Also tell us, what did you expect to happen?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: "Please copy and paste aomplete, minimal, self-contained example code that reproduces the issue. This will be automatically formatted into code, so no need for backticks."
      render: python
  - type: textarea
    id: addition-context
    attributes:
      label: Additional context
      placeholder: OS: [e.g. Linux 32bit], IDE: [e.g. Spyder, PyCharm]
